version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Ghibling
    ports:
      - "3306:3306"

#  springboot-app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
